### ISSUE TITLE
HTML tags corruption

### ISSUE THREAD

**Issue by Akkell** [PocketByte/LocoLaser#1]
**1. Bare HTML tags corruption.**
GoogleSheet: `key1	<b>Hello</b>`

Android:
- expected result: `<string name="key1"><b>Hello</b></string>`
- actual result: `<string name="key1">&lt;b>Hello&lt;/b></string>`

**2. HTML tags wrapped into `<![CDATA[ ...raw html... ]]>`**
GoogleSheet:
```
key1	<![CDATA[
<p>This is a html-formatted string with <b>bold</b> and <i>italic</i> text</p>
<p>This is another paragraph of the same string.</p>
]]>
```
Android:
- expected result: 
```
<string name="key1"><![CDATA[
<p>This is a html-formatted string with <b>bold</b> and <i>italic</i> text</p>
<p>This is another paragraph of the same string.</p>
]]></string>
```
- actual result: 
```
<string name="key1">&lt;![CDATA[\n&lt;p>This is a html-formatted string with &lt;b>bold&lt;/b> and &lt;i>italic&lt;/i> text&lt;/p>\n&lt;p>This is another paragraph of the same string.&lt;/p>\n]]></string>
```
Thank you for useful tool.

**Comment by KamiSempai** [comment]
LocoLaser escapes characters so in the TextView will be shown the same text as in Sheet. Also new line characters replaces with "\n". So described behaviour is expected behawiour.
I understand that in some cases the escaping not needed. It should be solved in the future by additional row attributes that defines how to handle such cases.
Until it done, if you want to use HTML formated string you should use programmaticaly way
`someTextView.setText(Html.fromHtml(someString));`

**Comment by KamiSempai** [comment]
CDATA bracers can be added by using [Meta Data](https://github.com/PocketByte/LocoLaser/blob/master/resource-mobile/README.md#metadata).  
To do it Google Sheet should contain meta data column with following value `"xml-cdata=true"`.  
Unfortunately there is no easy way to read CDATA bracers from `strings.xml`. So required metadata can be provided only from Google Sheet.
