### ISSUE TITLE
Multiple sources

### ISSUE THREAD

**Issue by PhilipDukhov** [PocketByte/LocoLaser#10]
I've split my strings in a couple worksheet in a single doc, added array to "source" field in config file, and faced a couple of problems:
1. looks like document gets downloaded each time, so script doesn't understand that it already has it downloaded - but it's only matter of 10 more seconds of build time which is not critical if it's hard to fix. 
2. strings are added randomly in the output file, so each time I run script git shows a lot of changes. this is more critical, can it be fixed?

**Comment by KamiSempai** [comment]
> 1. looks like document gets downloaded each time, so script doesn't understand that it already has it downloaded - but it's only matter of 10 more seconds of build time which is not critical if it's hard to fix.

Not totally whole document, but yes, this place should be optimized to reduce amount of requests.

> 2. strings are added randomly in the output file, so each time I run script git shows a lot of changes. this is more critical, can it be fixed?

Could you double check that strings are mixed up? For the first run git can show a lot of changes because of different line breakers.

**Comment by KamiSempai** [comment]
Since version 1.3.0 work with sheets has been optimized.
