### ISSUE TITLE
Strings with leading "+" lose it after export, import

### ISSUE THREAD

**Issue by Akkell** [PocketByte/LocoLaser#3]
Platform: Android
Steps:
1. Add string `+1` to strings.xml at the middle of list
2. Execute `localizeExportNew` Gradle task.
Look at strings.xml: `+1` string jumped at the top of list
Look at GSheet: strings appears as `=+1` in formula view, and `1` in a cell.
3. Execute `localize` Gradle task.
Look at strings.xml.

Expected: string is `+1`
Actual: string is `1`

Fix: add leading `'` to the string in GSheet, so it look `'+1`. I believe it should be done by the plugin.

**Comment by KamiSempai** [comment]
New version 1.0.1 released. This version contains fixes from current issue.
