### ISSUE TITLE
DerivedData folder

### ISSUE THREAD

**Issue by PhilipDukhov** [PocketByte/LocoLaser#9]
I'd changed TEMP_DIR to "$BUILD_DIR/LocoLaserTemp", and most of support files are created where expected, but locolaser.summary is created at ../DerivedData/LocoLaserTemp/ directory(relatively to my localize.command file), can I change this behavior?

**Comment by PhilipDukhov** [comment]
I've found "temp_dir" param in config file, but how can I pass $BUILD_DIR there? And what's the reason you've separated this files?

**Comment by KamiSempai** [comment]
LocoLazer is platform agnostic tool. It runs as separated JVM task, so it has no access to build environment variables. In general you shouldn't provide path to temporary directory cause each platform configuration has own default values for this parameter. But if you want to override it you should add parameter 'temp_dir' into JSON configuration file.
Currently, there is no way to use environment variables in configuration file. To help you somehow I will add run arguments '-temp_dir' and '-work_dir'. So you will be able to override them, using environment variables, in Run Script phase.

**Comment by KamiSempai** [comment]
Since version 1.3.0 can be used following console arguments: -workDir and -tempDir.
For example ./localize.command "--tempDir ../myTemp/"
